---
- name: Instalar Apache, PHP (con todos los módulos esenciales) y herramientas
  ansible.builtin.apt:
    name:
      # Paquetes base
      - apache2
      - unzip
      - curl
      - wget
      - python3-apt
      - mysql-client # Cliente para depuración de la DB
      
      # Paquetes PHP esenciales para WordPress
      - php-cli
      - libapache2-mod-php
      - php-mysql
      - php-gd
      - php-mbstring
      - php-xml
      - php-zip
    state: present
    update_cache: yes

- name: Habilitar el módulo reescribir (rewrite) de Apache
  community.general.apache2_module:
    state: present
    name: rewrite
  notify:
    - Reiniciar Apache

- name: Crear directorio temporal para descompresión
  ansible.builtin.file:
    path: /tmp/wordpress_unzip
    state: directory

- name: Descargar WordPress usando comando wget
  ansible.builtin.command: wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
  args:
    creates: /tmp/wordpress.tar.gz

- name: Descomprimir WordPress en el directorio temporal
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/wordpress_unzip/
    remote_src: yes
    creates: "/tmp/wordpress_unzip/wordpress"

- name: Mover contenido a /var/www/html/wordpress (evitando anidaciones dobles)
  ansible.builtin.copy:
    src: /tmp/wordpress_unzip/wordpress/
    dest: /var/www/html/wordpress/
    remote_src: yes
    owner: www-data
    group: www-data
    mode: preserve
    directory_mode: '0775'
    
- name: Eliminar directorios temporales y archivo .tar.gz
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/wordpress_unzip
    - /tmp/wordpress.tar.gz

- name: Copiar archivo de configuración wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0640'

- name: Arrancar y habilitar Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Comprobar que Apache responde con HTTP 200
  ansible.builtin.uri:
    url: http://localhost/wordpress
    status_code: 200
    timeout: 30
  register: result
  ignore_errors: true
